alias c='clear'
alias ccc='sudo rm ~/.ssh/known_hosts'
alias devdrop='ssh -i /root/.ssh/izzo root@165.22.10.26'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -al'
alias ls='ls --color=auto'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias scan='netdiscover -i eth0 -r 192.168.17.0/24'
