alias ocean='ssh root@174.138.61.74'
alias dropbox='ssh root@192.168.17.238'
alias scan='netdiscover -i eth0 -r 192.168.17.0/24'
alias ll='ls -al'
alias c='clear'
alias clearknownhosts='sudo rm ~/.ssh/known_hosts'
alias check='curl ipinfo.io'
alias ls='ls --color=auto'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
